baseurl = "https://luisnovaa.github.io"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Green&Novo"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = '"GO GREEN, there is not planet B"'
  mainSections = ["post","posts"]
  logo = "img/web-principal2" # Expecting square dimensions
  favicon = "img/stock_market_getty_images_29B_icon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Luis Nova"
  website = "lhnova.com"
  email = "hernando0018@.com"
  # facebook = "username"
  github = "luisnovaa"
  # gitlab = "username"
  # bitbucket = "username"
  # twitter = "username"
  # reddit = "username"
  linkedin = "username"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
  # 500px = "username"
  # codepen = "username"
  # mastodon = "url"
  # kaggle = "username"
  # weibo = "username"
  # slack = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "about"
    url = "about/about-my-site"
    weight = 3

[[menu.main]]
    identifier = "more information"
    name = "more information"
    url = "more-information/more-information-my-site"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Big Image Sample"
    url = "samples/samples-my-site"
    weight = 1

[[menu.main]]
    parent = "samples"
    name = "Math Sample"
    url = "samples/samples-my-site2"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Code Sample"
    url = "samples/2017-03-05-math-sample"
    weight = 3
